<a href="https://colab.research.google.com/github/bijaybenny/Epochs-Data-Science/blob/main/Day-2/analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving northwind.db to northwind.db

In [2]:
import sqlite3
conn = sqlite3.connect("northwind.db")

In [10]:
import pandas as pd

In [3]:
cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")

cursor.fetchall()

[('Categories',),
 ('sqlite_sequence',),
 ('CustomerCustomerDemo',),
 ('CustomerDemographics',),
 ('Customers',),
 ('Employees',),
 ('EmployeeTerritories',),
 ('Order Details',),
 ('Orders',),
 ('Products',),
 ('Regions',),
 ('Shippers',),
 ('Suppliers',),
 ('Territories',)]

In [12]:
query = """
SELECT
    Products.ProductName,
    SUM([Order Details].Quantity) AS TotalSold
FROM Products
JOIN [Order Details]
ON Products.ProductID = [Order Details].ProductID
GROUP BY Products.ProductName
ORDER BY TotalSold DESC
LIMIT 10;
"""
top_products = pd.read_sql_query(query, conn)
top_products

                       ProductName  TotalSold
0        Louisiana Hot Spiced Okra     206213
1           Sir Rodney's Marmalade     205637
2       Teatime Chocolate Biscuits     205487
3                   Sirop d'érable     205005
4              Gumbär Gummibärchen     204761
5                    Outback Lager     204403
6                   Ravioli Angelo     204251
7             Raclette Courdavault     204137
8  Uncle Bob's Organic Dried Pears     203970
9                    Sasquatch Ale     203667

In [14]:
query2 = """
SELECT
    Customers.CompanyName,
    ROUND(
        SUM([Order Details].UnitPrice *
            [Order Details].Quantity *
            (1 - [Order Details].Discount)
        ), 2
    ) AS Revenue
FROM Customers
JOIN Orders
    ON Customers.CustomerID = Orders.CustomerID
JOIN [Order Details]
    ON Orders.OrderID = [Order Details].OrderID
GROUP BY Customers.CompanyName
ORDER BY Revenue DESC
LIMIT 10;
"""

top_customers = pd.read_sql_query(query2, conn)

top_customers

                          CompanyName     Revenue
0                                  IT  9745371.29
1                       B's Beverages  6154115.34
2          Hungry Coyote Import Store  5698023.67
3                       Rancho grande  5559110.08
4                 Gourmet Lanchonetes  5552309.81
5  Ana Trujillo Emparedados y helados  5534356.65
6                  Ricardo Adocicados  5524517.31
7                   Folies gourmandes  5505502.85
8                   Let's Stop N Shop  5462198.02
9                   LILA-Supermercado  5437438.34

In [15]:
query3 = """
SELECT
    strftime('%Y-%m', Orders.OrderDate) AS Month,
    ROUND(
        SUM(
            [Order Details].UnitPrice *
            [Order Details].Quantity *
            (1 - [Order Details].Discount)
        ), 2
    ) AS Sales
FROM Orders
JOIN [Order Details]
    ON Orders.OrderID = [Order Details].OrderID
GROUP BY Month
ORDER BY Month;
"""

monthly_sales = pd.read_sql_query(query3, conn)

monthly_sales

       Month       Sales
0    2012-07  2066219.40
1    2012-08  3556875.79
2    2012-09  3440144.98
3    2012-10  3201529.96
4    2012-11  2980494.74
..       ...         ...
131  2023-06  3071787.73
132  2023-07  3350337.36
133  2023-08  3293158.67
134  2023-09  3544698.51
135  2023-10  2923364.35

[136 rows x 2 columns]

In [16]:
query4 = """
SELECT
    Categories.CategoryName,
    ROUND(
        SUM(
            [Order Details].UnitPrice *
            [Order Details].Quantity *
            (1 - [Order Details].Discount)
        ), 2
    ) AS Revenue
FROM Categories
JOIN Products
    ON Categories.CategoryID = Products.CategoryID
JOIN [Order Details]
    ON Products.ProductID = [Order Details].ProductID
GROUP BY Categories.CategoryName
ORDER BY Revenue DESC;
"""

category_sales = pd.read_sql_query(query4, conn)

category_sales

     CategoryName      Revenue
0       Beverages  92163184.18
1     Confections  66337803.07
2    Meat/Poultry  64881147.97
3  Dairy Products  58018116.79
4      Condiments  55795126.78
5         Seafood  49921604.17
6         Produce  32701119.88
7  Grains/Cereals  28568530.34

In [17]:
query5 = """
SELECT
    Customers.CompanyName,
    COUNT(DISTINCT Orders.OrderID) AS TotalOrders
FROM Customers
JOIN Orders
    ON Customers.CustomerID = Orders.CustomerID
GROUP BY Customers.CompanyName
ORDER BY TotalOrders DESC;
"""

purchase_frequency = pd.read_sql_query(query5, conn)

purchase_frequency

                             CompanyName  TotalOrders
0                                     IT          335
1                          B's Beverages          210
2                     Ricardo Adocicados          203
3                      LILA-Supermercado          203
4                    Gourmet Lanchonetes          202
..                                   ...          ...
87                       Around the Horn          156
88                  La corne d'abondance          155
89        Furia Bacalhau e Frutos do Mar          155
90  FISSA Fabrica Inter. Salchichas S.A.          155
91                Océano Atlántico Ltda.          154

[92 rows x 2 columns]